name: build

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up dotnet ${{ matrix.dotnet-version }} environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Run unit tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ./GitOps.Updater.Tests
    #   - name: Upload coverage to codecov.io
    #     uses: codecov/codecov-action@v4
    #     env:
    #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    #     with:
    #       file: ./tests/GitOps.Updater.Tests/coverage.opencover.xml